# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_Vietnam_Surgery_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_Vietnam_Surgery_App
  pod 'Alamofire'
  pod 'Eureka'
  pod 'SwiftKeychainWrapper'
  
end
